[package]
name = "russol-macros"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "^1.0", features = ["full", "parsing", "proc-macro", "printing", "visit-mut"] }
quote = "^1.0"
proc-macro2 = { version = "^1.0", features = ["span-locations"] }

[lib]
proc-macro = true
